
POST http://localhost:3000/login/
Content-Type:application/json
{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###



GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

###


GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

###



POST http://localhost:3000/districts/
Content-Type:application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw


{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
####


GET http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

###



DELETE  http://localhost:3000/districts/43/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

###




PUT http://localhost:3000/districts/46/
Content-Type:application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###


GET http://localhost:3000/states/3/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE1OTI0NjMxfQ.vOAteS9HwouIFn0yb17FZOs2TfnST4Dr9Dbgx099Amw

###






